source 'https://rubygems.org'


gem 'pg'
gem 'firebase'
gem 'sinatra', github: 'sinatra'
gem 'unirest'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'puma', '~> 3.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.2'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.5'
gem 'react-rails'
gem 'classnames-rails'

group :development, :test do
  gem 'byebug', platform: :mri
  gem 'rspec-rails'
  gem 'faker'
  gem 'factory_girl'
  gem 'guard-rspec', require: false
end

group :development do
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'capistrano', '~> 3.6'
  gem 'capistrano-rails', '~> 1.2'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'clearance'

gem 'sidekiq'
gem "sidekiq-cron", "~> 0.4.0"

gem 'figaro'
gem 'bcrypt'

gem 'omniauth-oauth2'

gem 'foreman'
gem 'rails_12factor'
gem 'redis'

gem 'paper_trail'
