# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

user_email: houston@next.com 
user_password: houston_good_to_go_123

fireb_apiKey: "AIzaSyCLKRXSFeRPrG5Vk_bZLY1zB0nXsyIqYt4"
fireb_authDomain: "project-houston.firebaseapp.com"
fireb_databaseURL: "https://project-houston.firebaseio.com"
fireb_storageBucket: "project-houston.appspot.com"
fireb_messagingSenderId: "234693173302"